[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_port = COM6
monitor_port = COM6

board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    bblanchon/ArduinoJson @ ^6.21.3
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.4
    mobizt/Firebase Arduino Client Library for ESP8266 and ESP32 @ ^4.4.14
